### ISSUE TITLE
Set postgres comments on tables and columns to help users

### ISSUE THREAD

**Issue by toolness** [aepyornis/nyc-db#88]
I found out that Postgres has a [`COMMENT` SQL command](https://www.postgresql.org/docs/10/sql-comment.html) that allows tables and columns (and other database entities) to be documented.  Here's an example:

```sql
CREATE TABLE boop( foo VARCHAR(50) );
COMMENT ON COLUMN boop.foo IS 'a funky thing';
```

When using `psql`, asking it for details on the table shows the comment for the column:

```
myuser=# \d+ boop
                                 Table "public.boop"
 Column |         Type          | Modifiers | Storage  | Stats target |  Description
--------+-----------------------+-----------+----------+--------------+---------------
 foo    | character varying(50) |           | extended |              | a funky thing
```

Some database clients like will also display these comments.  For example, [Postico](https://eggerapps.at/postico/) on OS X has a table design view that appears to display comments (though I'm not on OS X so I can't verify this).

If we have `nycdb` add comments for tables and columns, it could help new users (and even experienced ones) understand the structure of the data better.  One way we could do this is by changing the YAML structure of dataset metadata to also support objects for fields instead of strings, e.g.:

```yaml
# ...
schema:
  table_name: hpd_violations
  fields:
    # ...
    Block: integer
    Lot: integer
    Class:
        type: char(1)
        comment: |
            Indicator of seriousness of the violations, where A is the least serious
            and C is the most serious.
    InspectionDate: date
    ApprovedDate: date
    # ...
```

Anyways, just an idea.  Along with #85 this could help folks acclimatize to NYC-DB better.
